---
version: "2.1"
services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ./config:/config
      - <path to downloads>:/downloads
      - <path to incomplete-downloads>:/incomplete-downloads #optional
    ports:
      - 8081:8080
      - 9091:9090
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - UMASK_SET=022 #optional
    volumes:
      - ./config:/config
      - <path to movies>:/movies
      - <path to downloads>:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  pyload:
    image: writl/pyload:latest
    container_name: pyload
    ports:
      - 8001:8000
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ./pyload_config:/opt/pyload/pyload-config
      - <path to downloads>:/opt/pyload/Downloads
    restart: always

